repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.0
    hooks:
      - id: terraform_fmt
        files: ^terraform/(environments/dev/api-service/(eks-core|eks-karpenter|eks-irsa)|modules/api-service/(eks-core|eks-karpenter|eks-irsa)|environments/dev/ssm-parameters)/
      - id: terraform_validate
        #stages: [manual]
        files: ^terraform/(environments/dev/api-service/(eks-core|eks-karpenter|eks-irsa)|modules/(eks-core|eks-karpenter|eks-irsa))/
      - id: terraform_tflint
        files: ^terraform/(environments/dev/api-service/(eks-core|eks-karpenter|eks-irsa)|modules/(eks-core|eks-karpenter|eks-irsa))/
      - id: terraform_docs
        #stages: [manual]
        files: ^terraform/(environments/dev/api-service/(eks-core|eks-karpenter|eks-irsa)|modules/(eks-core|eks-karpenter|eks-irsa))/
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
