{{- if .Values.nodePools.default.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    metadata:
      labels:
        {{- toYaml .Values.nodePools.default.labels | nindent 8 }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.nodeClass.name }}
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: {{ toJson .Values.nodePools.default.requirements.arch }}
        - key: kubernetes.io/os
          operator: In
          values: {{ toJson .Values.nodePools.default.requirements.os }}
        - key: karpenter.sh/capacity-type
          operator: In
          values: {{ toJson .Values.nodePools.default.requirements.capacityType }}
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: {{ toJson .Values.nodePools.default.requirements.instanceCategory }}
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: [{{ .Values.nodePools.default.requirements.instanceGeneration | quote }}]
  limits:
    cpu: {{ .Values.nodePools.default.limits.cpu | quote }}
    memory: {{ .Values.nodePools.default.limits.memory }}
  disruption:
    consolidationPolicy: {{ .Values.nodePools.default.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.nodePools.default.disruption.consolidateAfter }}
{{- end }}
