apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: {{ .Values.clusterSecretStore.provider.service }}
      region: {{ .Values.clusterSecretStore.provider.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.serviceAccountRef.name }}
            namespace: {{ .Values.clusterSecretStore.serviceAccountRef.namespace }}
